In [38]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
data = pd.read_csv("Multiple.csv")

#### Label Encoding

In [39]:
data["EducationLevel"] = data["EducationLevel"].map({"高中以下": 0, "大學": 1, "碩士以上": 2})

#### One-Hot Encoder

In [40]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder()
onehotencoder.fit(data[["City"]])
city_encoded = onehotencoder.transform(data[["City"]])# return 稀疏矩陣
city_encoded = city_encoded.toarray()

In [41]:
data[["CityA","CityB","CityC"]] = city_encoded
data = data.drop(["City","CityC"],axis=1)

In [42]:
from sklearn.model_selection import train_test_split
import numpy as np
x = data[["YearsExperience","EducationLevel","CityA","CityB"]]
y = data[["Salary"]]

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=87)
x_train = x_train.to_numpy()
y_train =  y_train.to_numpy()
x_test = x_test.to_numpy()
y_test = y_test.to_numpy()

In [43]:
w = np.array([1,2,3,4])
b = 1
y_pred = (x_train*w).sum(axis=1)+ b

#### Cost Function

In [44]:
def compute_cost(x, y, w, b):
  y_pred = (x*w).sum(axis=1) + b
  cost = ((y - y_pred)**2).mean()
  return cost

In [45]:
w = np.array([0, 2, 2, 4])
b = 0
cost = compute_cost(x_train, y_train, w, b)
cost

np.float64(2477.394285714286)

In [46]:
y_pred = (x_train*w).sum(axis=1) +b
b_gradient = (y_pred - y_train).mean()
w_gradient = np.zeros(x_train.shape[1])


for i in range(x_train.shape[1]):
    w_gradient[i] = (x_train[:,i]*(y_pred-y_train)).mean()
w_gradient,b_gradient
# w1_gradient = (x_train[:,0]*(y_pred-y_train)).mean()
# w1_gradient

(array([-2.74e+02, -5.42e+01, -2.54e+01, -6.14e+00]),
 np.float64(-46.949999999999996))

In [47]:
def compute_gradient(x, y, w, b):
  y_pred = (x*w).sum(axis=1) + b
  w_gradient = np.zeros(x.shape[1])
  b_gradient = (y_pred - y).mean()
  for i in range(x.shape[1]):
    w_gradient[i] = (x[:, i]*(y_pred - y)).mean()

  return w_gradient, b_gradient

In [48]:
w = np.array([1,2,2,4])
b = 1
compute_gradient(x_train, y_train, w, b)

(array([-2.26e+02, -4.52e+01, -2.25e+01, -4.56e+00]),
 np.float64(-40.07142857142858))

In [49]:
w = np.array([1,2,2,4])
b = 1
learning_rate = 1.0e-3
w_gradient,b_gradient = compute_gradient(x_train, y_train, w, b)
print(compute_cost(x_train, y_train, w, b))
w = w - w_gradient*learning_rate
b = b - b_gradient*learning_rate
w,b
print(compute_cost(x_train, y_train, w, b))

1890.4221428571427
1781.9761478950202


In [50]:
np.set_printoptions(formatter={'float': '{: .2e}'.format})
def gradient_descent(x, y, w_init, b_init, learning_rate, cost_function, gradient_function, count, p_iter=1000):

  c_hist = []
  w_hist = []
  b_hist = []

  w = w_init
  b = b_init

  for i in range(count):
    w_gradient, b_gradient = compute_gradient(x, y, w, b)

    w = w - w_gradient*learning_rate
    b = b - b_gradient*learning_rate
    cost = cost_function(x, y, w, b)

    w_hist.append(w)
    b_hist.append(b)
    c_hist.append(cost)

    if i%p_iter == 0:
      print(f"Iteration {i:5} : Cost {cost: .4e}, w: {w}, b: {b: .2e}, w_gradient: {w_gradient}, b_gradient: {b_gradient: .2e}")

  return w, b, w_hist, b_hist, c_hist

In [51]:
w_init = np.array([1,2,2,4])
b_init = 0
learning_rate = 1.0e-3
count = 10000

w_final, b_final, w_hist, b_hist, c_hist = gradient_descent(x_train, y_train, w_init, b_init, learning_rate,compute_cost, compute_gradient,count )

Iteration     0 : Cost  1.8574e+03, w: [ 1.23e+00  2.05e+00  2.02e+00  4.00e+00], b:  4.11e-02, w_gradient: [-2.32e+02 -4.64e+01 -2.31e+01 -4.71e+00], b_gradient: -4.11e+01
Iteration  1000 : Cost  4.3703e+02, w: [ 4.86e+00  4.52e+00  9.54e+00  1.48e+00], b:  6.85e+00, w_gradient: [ 1.16e+00 -1.19e+00 -5.30e+00  2.15e+00], b_gradient: -4.88e+00
Iteration  2000 : Cost  3.6212e+02, w: [ 3.94e+00  5.46e+00  1.35e+01 -2.72e-01], b:  1.09e+01, w_gradient: [ 7.28e-01 -7.23e-01 -2.83e+00  1.42e+00], b_gradient: -3.31e+00
Iteration  3000 : Cost  3.3343e+02, w: [ 3.35e+00  6.01e+00  1.55e+01 -1.45e+00], b:  1.37e+01, w_gradient: [ 4.65e-01 -4.09e-01 -1.39e+00  9.73e-01], b_gradient: -2.37e+00
Iteration  4000 : Cost  3.2118e+02, w: [ 2.97e+00  6.31e+00  1.65e+01 -2.27e+00], b:  1.57e+01, w_gradient: [ 3.04e-01 -1.99e-01 -5.60e-01  6.95e-01], b_gradient: -1.80e+00
Iteration  5000 : Cost  3.1491e+02, w: [ 2.72e+00  6.44e+00  1.68e+01 -2.87e+00], b:  1.73e+01, w_gradient: [ 2.06e-01 -6.15e-02 -8.07e

In [52]:
w_final,b_final

(array([ 2.18e+00,  6.02e+00,  1.52e+01, -4.39e+00]),
 np.float64(22.658670502289073))

In [59]:
y_pred = (w_final*x_test).sum(axis=1) + b_final
pd.DataFrame({
    "y_pred": y_pred,
    "y_test": y_test
})

ValueError: Per-column arrays must each be 1-dimensional